server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/shopping-mall
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jwt:
    secret: wonseok
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          #show_sql: false
          format_sql: true
          default_batch_fetch_size: 100
logging:
  level:
    org.hibernate.SQL: debug

custom:
  path:
    upload: C:\\